<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'supplier', 'as' => 'supplier.', 'namespace' => 'Supplier', 'middleware' => ['auth', '2fa']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // Task
    Route::delete('tasks/destroy', 'TaskController@massDestroy')->name('tasks.massDestroy');
    Route::post('tasks/media', 'TaskController@storeMedia')->name('tasks.storeMedia');
    Route::post('tasks/ckmedia', 'TaskController@storeCKEditorImages')->name('tasks.storeCKEditorImages');
    Route::resource('tasks', 'TaskController');

    // Tasks Calendar
    // TODO: Commented because its maybe wrongly generated by QuickAdminPanel's bug. Might need to delete in future.
    // Route::resource('tasks-calendars', 'TasksCalendarController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Project
    Route::delete('projects/destroy', 'ProjectController@massDestroy')->name('projects.massDestroy');
    Route::post('projects/media', 'ProjectController@storeMedia')->name('projects.storeMedia');
    Route::post('projects/ckmedia', 'ProjectController@storeCKEditorImages')->name('projects.storeCKEditorImages');
    Route::resource('projects', 'ProjectController');

    // Open Project
    Route::delete('open-projects/destroy', 'OpenProjectController@massDestroy')->name('open-projects.massDestroy');
    Route::post('open-projects/media', 'OpenProjectController@storeMedia')->name('open-projects.storeMedia');
    Route::post('open-projects/ckmedia', 'OpenProjectController@storeCKEditorImages')->name('open-projects.storeCKEditorImages');
    Route::resource('open-projects', 'OpenProjectController');

    // Supplier Proposal
    Route::delete('supplier-proposals/destroy', 'SupplierProposalController@massDestroy')->name('supplier-proposals.massDestroy');
    Route::post('supplier-proposals/media', 'SupplierProposalController@storeMedia')->name('supplier-proposals.storeMedia');
    Route::post('supplier-proposals/ckmedia', 'SupplierProposalController@storeCKEditorImages')->name('supplier-proposals.storeCKEditorImages');
    Route::resource('supplier-proposals', 'SupplierProposalController');

    Route::get('frontend/profile', 'ProfileController@index')->name('profile.index');
    Route::post('frontend/profile', 'ProfileController@update')->name('profile.update');
    Route::post('frontend/profile/destroy', 'ProfileController@destroy')->name('profile.destroy');
    Route::post('frontend/profile/password', 'ProfileController@password')->name('profile.password');
    Route::post('profile/toggle-two-factor', 'ProfileController@toggleTwoFactor')->name('profile.toggle-two-factor');
});
